# Generated by Django 2.0.4 on 2018-09-07 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LabeledData',
            fields=[
                ('labeled_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_content', models.CharField(max_length=100)),
                ('labeled_time', models.DateTimeField()),
                ('labeled_content', models.CharField(max_length=120)),
                ('predicted_relation', models.CharField(max_length=20)),
                ('predicted_e1', models.CharField(max_length=20)),
                ('predicted_e2', models.CharField(max_length=20)),
                ('labeled_relation', models.CharField(max_length=20)),
                ('labeled_e1', models.CharField(max_length=20)),
                ('labeled_e2', models.CharField(max_length=20)),
                ('additional_info', models.CharField(max_length=30)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.FileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnLabeledData',
            fields=[
                ('unlabeled_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_content', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.FileInfo')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.ProjectInfo')),
            ],
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.ProjectInfo'),
        ),
    ]
