# Generated by Django 2.0.4 on 2018-09-07 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_labeleddata_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='project_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=10, unique=True), default=[], size=None),
        ),
    ]
