# Generated by Django 2.0.4 on 2018-09-07 13:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_projectinfo_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=20, unique=True), default=[], size=None),
        ),
    ]
