# Generated by Django 2.1.7 on 2019-04-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_auto_20190415_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetags',
            name='tag_name',
        ),
        migrations.AlterField(
            model_name='labeleddata',
            name='additional_info',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labeleddata',
            name='labeled_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='labeleddata',
            name='labeled_e1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='labeleddata',
            name='labeled_e2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='labeleddata',
            name='labeled_relation',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='labeleddata',
            name='predicted_e1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='labeleddata',
            name='predicted_e2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='labeleddata',
            name='predicted_relation',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='unlabeleddata',
            name='data_content',
            field=models.TextField(),
        ),
    ]
