# Generated by Django 2.1.7 on 2019-04-24 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0005_auto_20190424_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeleddata',
            name='e1',
        ),
        migrations.RemoveField(
            model_name='labeleddata',
            name='e2',
        ),
        migrations.RemoveField(
            model_name='labeleddata',
            name='labeled_e1',
        ),
        migrations.RemoveField(
            model_name='labeleddata',
            name='labeled_e2',
        ),
    ]
