# Generated by Django 2.1.7 on 2019-04-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0007_auto_20190424_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='labeleddata',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='unlabeleddata',
            name='file_id',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
